### ISSUE TITLE
Crashing in mini fig search

### ISSUE THREAD

**Issue by RandomLozza** [leolelego/Brickie-iOS#92] opened 2021-09-06 14:10 UTC
I haven’t used the mini fig section yet but today I wanted to add some and the app keeps closing down when I use the mini fig search button.

I’m using iOS14.4.2

**Comment by leolelego** [comment] 2021-09-06 14:27
Hi @RandomLozza 

Are you able to provide one or more. this:
- a video
- the set search (number, name ...)

Also, are you able to update to the last iOS 14 update: 14.7.1 and if you can does it solve the issue.

**Comment by leolelego** [comment] 2021-11-11 10:42
Closing for now update.  Can't reproduce. Feel free to open back if you can provide any video or way to reproduce.

**Closed by leolelego** 2021-11-11 10:42 UTC
